apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJWRU5oZEdobGNtbHVaVHBuYUhCZmQwOW1Sbk5HVEhKcFNsSkRNbUZRU25nNVZHdE9VMjVFY1djd1RWbzFORkpUVUVwMCIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQo=
type: kubernetes.io/dockerconfigjson
