# Global settings
global:
  namespace: cinemaabyss
  domain: cinemaabyss.example.com

# Image pull secrets
imagePullSecrets:
  dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJWRU5oZEdobGNtbHVaVHBuYUhCZmQwOW1Sbk5HVEhKcFNsSkRNbUZRU25nNVZHdE9VMjVFY1djd1RWbzFORkpUVUVwMCIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQo=
# Database configuration
database:
  host: postgres
  port: 5432
  name: cinemaabyss
  user: postgres
  password: cG9zdGdyZXNfcGFzc3dvcmQ=
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 52Mi
  persistence:
    enabled: true
    size: 256Mi
    accessMode: ReadWriteOnce
    storageClass: local-path

# Monolith configuration
monolith:
  enabled: true
  image:
    repository: ghcr.io/tcatherine/architecture-course-cinemaabyss/monolith
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8080
    targetPort: 8080
    type: ClusterIP

# Proxy service configuration
proxyService:
  enabled: true
  image:
    repository: ghcr.io/tcatherine/architecture-course-cinemaabyss/proxy-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  cfg:
    monolith_url: "http://monolith:8080"
    movies_service_url: "http://movies-service:8081"
    events_service_url: "http://events-service:8082"
    gradual_migration: "true"
    movies_migration_percent: "50"
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 128Mi
  service:
    port: 80
    targetPort: 8000
    type: ClusterIP

# Movies service configuration
moviesService:
  enabled: true
  image:
    repository: ghcr.io/tcatherine/architecture-course-cinemaabyss/movies-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8081
    targetPort: 8081
    type: ClusterIP

# Events service configuration
eventsService:
  enabled: true
  image:
    repository: ghcr.io/tcatherine/architecture-course-cinemaabyss/events-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8082
    targetPort: 8082
    type: ClusterIP
  cfg:
    kafka_brokers: kafka.cinemaabyss:9092

# Kafka configuration
kafka:
  enabled: true
  image:
    repository: apache/kafka
    tag: 4.1.1
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: "52Mi"
      cpu: "20m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  persistence:
    enabled: true
    size: 128Mi
    accessMode: ReadWriteOnce
    storageClass: local-path

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: cinemaabyss.example.com
      paths:
        - path: /
          pathType: Prefix
          service: proxy-service
          port: 80
        - path: /api/events
          pathType: Prefix
          service: events-service
          port: 8082

# Application configuration
config:
  # Strangler Fig configuration
  gradualMigration: "true"
  moviesMigrationPercent: "100"
